name: Create Container Image (ASP.NET Core WebApi)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_PATH: './WebApiProj'
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      
      - name: Build the project
        run: dotnet build ${{ env.APP_PATH }} --configuration Release

  push:
    runs-on: ubuntu-latest
    env:
      APP_PATH: './WebApiProj'
    needs: build

    steps:
      - uses: actions/checkout@v3
        
      - name: Login via Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGINSERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Docker Build
        run: docker build . -t ${{ secrets.REGISTRY_LOGINSERVER }}/webapi:${{ github.sha }} -f ${{ env.APP_PATH }}/Dockerfile
      
      - name: Docker Push
        run: docker push ${{ secrets.REGISTRY_LOGINSERVER }}/webapi:${{ github.sha }}
