name: Deploy Database project to Azure SQL Database

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    env:
      PRJ_PATH: 'SQL_DB_Project'

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
      
      - name: Build the database project
        run: dotnet build ${{ env.PRJ_PATH }}/*.sqlproj -c Release
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: db-project
          path: ${{ env.PRJ_PATH }}/bin/Release

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Download artifact for deployment job
        uses: actions/download-artifact@v2
        with:
          name: db-project
      
      - name: Deploy the database project
        uses: azure/sql-action@v2.3
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './SQL_DB_Project.dacpac'
          action: Publish
          arguments: '/p:DropObjectsNotInSource=false'