name: Deploy Database project to Azure SQL Database

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    env:
      PRJ_PATH: 'SQL_DB_Project'

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
      
      - name: Build the database project
        run: dotnet build ${{ env.PRJ_PATH }}/*.sqlproj -c Release
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: db-project
          path: ${{ env.PRJ_PATH }}/bin/Release

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Install Azure CLI
        run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli
      
      - name: Install SqlPackage
        run: |
          dotnet tool install -g microsoft.sqlpackage

      - name: Log into Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download artifact for deployment job
        uses: actions/download-artifact@v2
        with:
          name: db-project
          path: Release
      
      - name: Deploy the database project
        uses: azure/sql-action@v2
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: ./Release/SQL_DB_Project.dacpac
          action: Publish
          arguments: '/p:DropObjectsNotInSource=false'
      
      - name: Clean up
        run: |
          az logout